version: '3.8'

volumes:
  mysql-data:

services:
  web:
    image: nginx:1.18
    ports:
      - '88:80'
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/:/var/www/html
  app:
    build: ./docker/php
    volumes:
      - ./src/:/var/www/html
    ports:
      - '3000:3000'
  db:
    image: mysql:5.7
    ports:
      - '7306:3306'
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${USER_NAME}
      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-data:/var/lib/mysql
  db_test:
    image: mysql:5.7
    ports:
      - '7307:3306'
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME_TEST}
      MYSQL_USER: ${USER_NAME_TEST}
      MYSQL_PASSWORD: ${PASSWORD_TEST}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    tmpfs:
      - /var/lib/mysql
      - /var/log/mysql